version: '3.8'
services:
  ca.example.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      # 필요에 따라 추가 환경 변수 설정
    ports:
      - "7055:7054"
    volumes:
      - ./ca-server-data:/etc/hyperledger/fabric-ca-server
